In [5]:
import pickle
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [6]:
model = pickle.load(open("model.sav","rb"))
scaler = pickle.load(open("scaler1.sav","rb"))
weather= pickle.load(open("label_weathertype.sav","rb"))

In [7]:
import pandas as pd
import pickle

df = pd.read_csv('weather.csv ')

lb = pickle.load(open('label_cloudcover.sav','rb'))
lb1 = pickle.load(open('label_season.sav','rb'))
lb2 = pickle.load(open('label_location.sav','rb'))
lb3 = pickle.load(open('label_weathertype.sav','rb'))

df['Cloud Cover'] = lb.transform(df['Cloud Cover'])
df['Season'] = lb1.transform(df['Season'])
df['Location'] = lb2.transform(df['Location'])



In [8]:
Temperature=float(input('enter the Temperature : '))

Humidity=float(input('enter the humidity : '))

Wind_Speed=float(input('enter the wind speed : '))

Precipitation=float(input('enter the Precipitation : '))

Cloud_Cover=input('enter the cloud cover : ')
CloudCover_obj=pickle.load(open('label_cloudcover.sav','rb'))
Cloud_Cover1=CloudCover_obj.transform([[Cloud_Cover]])

Atmospheric_Pressure=float(input('enter the atmospheric pressure : '))

UV_Index=float(input('enter the UV index :'))

Season=input('enter the season : ')
Season_obj=pickle.load(open('label_season.sav','rb'))
Season1=Season_obj.transform([[Season]])

Visibility=float(input('enter the visibility : '))

Location=input('enter the location : ')
Location_obj=pickle.load(open('label_location.sav','rb'))
Location1=Location_obj.transform([[Location]])

e:\DATA SCIENCE\ML\Project\ml_project\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
e:\DATA SCIENCE\ML\Project\ml_project\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
e:\DATA SCIENCE\ML\Project\ml_project\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [9]:
import numpy as np

In [10]:
new_data=np.array([Temperature,Humidity])
new_data

array([14., 73.])

In [11]:
new_data = np.concatenate((np.array([Wind_Speed]), new_data))
new_data

array([ 9., 14., 73.])

In [12]:
new_data = np.concatenate((new_data, np.array([Precipitation])))
new_data

array([ 9., 14., 73., 82.])

In [13]:
data=np.array([Atmospheric_Pressure,UV_Index,Visibility])


In [14]:
new_data=np.concatenate((new_data,data))
new_data

array([   9.,   14.,   73.,   82., 1010.,    2.,    5.])

In [15]:
new_data1 = np.concatenate([np.array([[Cloud_Cover1]]), 
                            np.array([[Season1]])], axis=1)
new_data1

array([[[0],
        [3]]])

In [16]:
new_data1 = np.array(new_data1).reshape(new_data1.shape[0], -1)

rows = new_data1.shape[0]
Location2 = np.array([Location1] * rows).reshape(-1, 1)





In [17]:
new_data1 = np.concatenate([new_data1, Location2], axis=1)
print(new_data1)

[[0 3 1]]


In [18]:
new_data=new_data.reshape(1,-1)
new_data

array([[   9.,   14.,   73.,   82., 1010.,    2.,    5.]])

In [19]:
new_data = np.repeat(new_data, new_data1.shape[0], axis=0)
pred_data = np.concatenate([new_data, new_data1], axis=1)

In [20]:
with open("label_weathertype.sav", "rb") as f:
    lb3 = pickle.load(f)

In [21]:

df['Weather Type_encoded'] = lb3.transform(df['Weather Type'])



In [22]:

df['Weather Type_decoded'] = lb3.inverse_transform(df['Weather Type_encoded'])



In [23]:
scalar = pickle.load(open('scaler1.sav','rb'))

In [24]:
pred_data

array([[9.00e+00, 1.40e+01, 7.30e+01, 8.20e+01, 1.01e+03, 2.00e+00,
        5.00e+00, 0.00e+00, 3.00e+00, 1.00e+00]])

In [25]:
prediction = scalar.transform(pred_data)

e:\DATA SCIENCE\ML\Project\ml_project\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [26]:
prediction

array([[-6.27490273e-01, -2.94420327e+00,  1.15727977e+01,
         9.70217670e-01,  9.88938313e+02, -7.87924218e+01,
         5.14368394e-01, -1.61625118e+00, -8.16564003e-01,
        -1.40128501e-01]])

In [27]:
model= pickle.load(open('model.sav','rb'))

In [28]:
predicted_weather = model.predict(prediction)
predicted_weather
print("Encoded prediction:", predicted_weather)



decoded = weather.inverse_transform(predicted_weather)
print("Predicted Weather Type:", decoded[0])

Encoded prediction: [0]
Predicted Weather Type: Cloudy
